crisischeckin/crisicheckinweb/ViewModels/DisasterViewModel.cs
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace crisicheckinweb.ViewModels
{
    public class DisasterViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Disaster name")]
        [RegularExpression("^[A-Za-z0-9,. ]*$", ErrorMessageResourceName = "InvalidDisasterName", ErrorMessageResourceType=typeof(Resources.DefaultErrorMessages))]
        public string Name { get; set; }

        [DisplayName("Currently active")]
        public bool IsActive { get; set; }

        public List<SelectedDisasterCluster> SelectedDisasterClusters { get; set; }
    }
}

crisischeckin/crisicheckinweb/Controllers/DisasterController.cs
using crisicheckinweb.Filters;
using crisicheckinweb.ViewModels;
using Models;
using Services.Exceptions;
using Services.Interfaces;
using System;
using System.Linq;
using System.Web.Mvc;

namespace crisicheckinweb.Controllers
{
    [AccessDeniedAuthorize(Roles = Common.Constants.RoleAdmin, AccessDeniedViewName = "~/Home/AccessDenied")]
    public class DisasterController : BaseController
    {
        private readonly IDisaster _disasterSvc;
        private readonly ICluster _clusterSvc;
        private readonly IDisasterClusterService _disasterClusterSvc;

        public DisasterController(IDisaster disasterSvc, ICluster clusterSvc, IDisasterClusterService disasterClusterSvc)
        {
            _disasterSvc = disasterSvc;
            _clusterSvc = clusterSvc;
            _disasterClusterSvc = disasterClusterSvc;
        }

        // GET: /Disaster/
        public ActionResult List()
        {
            var viewData = _disasterSvc.GetList().ToList()
                .Select(CreateViewModel);

            return View(viewData);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            int disasterId;
            var validId = int.TryParse(id, out disasterId);

            if (validId && disasterId != -1)
            {
                var disaster = _disasterSvc.Get(disasterId);
                return View("Create", CreateViewModel(disaster));
            }
            return View("Create", new DisasterViewModel
            {
                IsActive = true,
                SelectedDisasterClusters = (from list in _clusterSvc.GetList()
                                            select new SelectedDisasterCluster 
                                            { Name = list.Name, Id = list.Id, Selected = true }).ToList()
            });
        }

        [HttpPost]
        public ActionResult Create(DisasterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!model.SelectedDisasterClusters.Exists(x => x.Selected == true))
                    {
                        ModelState.AddModelError("Name", "You have to include at least one Cluster!");
                        return View("Create", model);
                    }

                    var disaster = new Disaster
                    {
                        Id = model.Id,
                        Name = model.Name,
                        IsActive = model.IsActive
                    };

                    var newClusterList = (from selectedList in model.SelectedDisasterClusters
                                          join clusterList in _clusterSvc.GetList()
                                          on selectedList.Id equals clusterList.Id into outerList
                                          from clusterList in outerList.DefaultIfEmpty()
                                          where clusterList == null
                                          select new Cluster { Name = selectedList.Name, Id = selectedList.Id}).ToList();

                    foreach (var item in newClusterList)
                    {
                        _clusterSvc.Create(item);
                    }

                    if (model.Id == -1)
                    {
                        _disasterSvc.Create(disaster);

                        var id = _disasterSvc.GetList().Where(x => x.Name == model.Name).FirstOrDefault().Id;

                        foreach (var item in model.SelectedDisasterClusters)
                        {
                            if (item.Selected == true)
                            {
                                if (newClusterList.Exists(x => x.Name == item.Name))
                                {
                                    _disasterClusterSvc.Create(new DisasterCluster { Id = -1, DisasterId = id, Cluster = newClusterList.Find(x => x.Name == item.Name) });
                                }
                                else
                                {
                                    _disasterClusterSvc.Create(new DisasterCluster { Id = -1, DisasterId = id, ClusterId = item.Id });
                                }
                            }
                        }
                    }
                    else
                    {
                        _disasterSvc.Update(disaster);

                        var disasterClusterList = _disasterClusterSvc.GetClustersForADisaster(model.Id);

                                       
                        foreach (var item in model.SelectedDisasterClusters)
                        {
                            if (item.Selected == true)
                            {
                                if (!disasterClusterList.Exists(x => x.ClusterId == item.Id))
                                {
                                    _disasterClusterSvc.Create(new DisasterCluster { Id = -1, DisasterId = model.Id, ClusterId = item.Id });
                                }
                            }
                            else
                            {
                                if (disasterClusterList.Exists(x => x.ClusterId == item.Id))
                                {
                                    _disasterClusterSvc.Remove(disasterClusterList.Find(x => x.ClusterId == item.Id));
                                }
                            }
                        }
                    }
                }
                catch (DisasterAlreadyExistsException)
                {
                    ModelState.AddModelError("Name", "A Disaster already exists with that Name!");
                    return View("Create", model);
                }

                return Redirect("/Disaster/List");
            }
            return View("Create", model);
        }

        //TODO: Need to set a schedule for removal.
        [HttpPost]
        [Obsolete("POST /Edit is deprecated. Use POST /Create instead")]
        public ActionResult Edit(DisasterViewModel model)
        {
            TempData["EditUrlDeprecatedWarning"] = "POST /Edit is deprecated. Use POST /Create instead";
            return Create(model);
        }

        private DisasterViewModel CreateViewModel(Disaster disaster)
        {
            return new DisasterViewModel
            {
                Id = disaster.Id,
                Name = disaster.Name,
                IsActive = disaster.IsActive,
                SelectedDisasterClusters =
                    (from clustList in _clusterSvc.GetList()
                     join disList in _disasterClusterSvc.GetClustersForADisaster(disaster.Id)
                     on clustList.Id equals disList.ClusterId into outerList
                     from disList in outerList.DefaultIfEmpty()
                     select new SelectedDisasterCluster 
                     { Name = clustList.Name, Id = clustList.Id, Selected = (disList != null)}).ToList()
            };
        }

        #region api methods

        public JsonResult GetActiveDisasters()
        {
            return Json(_disasterSvc.GetActiveList(), JsonRequestBehavior.AllowGet);
        }

        #endregion api methods
    }
}

crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
@model crisicheckinweb.ViewModels.DisasterViewModel
@{
    ViewBag.Title = "Create / Edit Disaster";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Create", "Disaster"))
{
    @Html.HiddenFor(m => m.Id)
    <h3>Create / Edit Disaster</h3>
    @Html.ValidationSummary()
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.CheckBoxFor(m => m.IsActive)
                @Html.LabelFor(m => m.IsActive)
            </div>
            <input type="submit" value="@(Model.Id > 0 ? "Update" : "Create") Disaster" class="btn btn-success" />
        </div>
        <div class="col-sm-8">
            <div>
                <h4>Clusters assigned to the disaster</h4>
                <table class="table table-striped table-bordered table-condensed" cellpadding="0" cellspacing="0" border="1">
                    <tbody>
                        <tr class="ht-header">
                            <th class="col-md-1">Using</th>
                            <th class="col-md-11">Cluster Name</th>
                        </tr>
                        <tr class="ht-utility">
                            <td class="text-center">
                                <input type="checkbox" checked="checked" data-val="true" 
                                       id="SelectedDisasterClustersAll" 
                                       name="SelectedDisasterClustersAll" 
                                       value="true">
                            </td>
                            <td>(Select All)</td>
                        </tr>
                        @for (int i = 0; i < Model.SelectedDisasterClusters.Count; i++)
                        {
                            <tr>
                                <td class="text-center">@Html.CheckBoxFor(s => s.SelectedDisasterClusters[i].Selected)</td>
                                <td>
                                    @Html.DisplayFor(s => s.SelectedDisasterClusters[i].Name)
                                    @Html.HiddenFor(s => s.SelectedDisasterClusters[i].Id)
                                    @Html.HiddenFor(s => s.SelectedDisasterClusters[i].Name)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                        @if (Request.Url.Segments.Length > 3)
                {
                            @Html.ActionLink("Add New Cluster", "../Cluster/Create", new { DisasterId = Request.Url.Segments[3] }, new { @class = "btn btn-black pull-right" })
                        }

            </div>


        </div>
    </div>
}

@section scripts
{
    <script src="~/scripts/App/disasterEdit.js"></script>
}

crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml
@model IEnumerable<crisicheckinweb.ViewModels.DisasterViewModel>
@{
    ViewBag.Title = "List of Disasters";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    table, tr, th, td {
        padding: 7px;
        border: 1px solid grey;
    }
</style>

<h3>List of Disasters</h3>

                      <div class="pull-right">
                          @Html.ActionLink("Add New Disaster", "Edit", new { id = -1 }, new { @class = "btn btn-black" })
                          @Html.ActionLink("Add New Cluster", "../Cluster/Create", new { }, new { @class = "btn btn-black" })
                          @Html.ActionLink("Add New Cluster Group", "../ClusterGroup/Create", new { }, new { @class = "btn btn-black" })
                          @Html.ActionLink("Cluster List", "../Cluster/List", new { }, new { @class = "btn btn-black" })          
                          @Html.ActionLink("Cluster Group List", "../ClusterGroup/List", new { }, new { @class = "btn btn-black" })
                                    
                      </div>
<br />
<br />
<table class="table table-striped table-bordered" cellpadding="0" cellspacing="0" border="1">
    <tr class="ht-header">
        <th width="300px;">Disaster Name</th>
        <th>Is Active?</th>
        <th></th>
    </tr>
    @foreach (var d in Model)
    {
        <tr>
            <td>@d.Name</td>
            <td>@d.IsActive</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = d.Id })
                @if (d.IsActive)
                {
                    <text>|</text>
                    @Html.ActionLink("Send Message to Volunteers", "CreateMessageToVolunteersByDisaster", new { controller = "Volunteer", d.Id })
                    <text>|</text>
                    @Html.ActionLink("Cluster Coordinators", "Index", new { controller = "ClusterCoordinator", d.Id })
                }
            </td>
        </tr>
    }
</table>
