crisischeckin/crisicheckinweb/ViewModels/ClusterCoordinatorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace crisicheckinweb.ViewModels
{
    public class ClusterCoordinatorViewModel
    {
        [StringLength(61)]
        public string Name { get; set; }
        public int Id { get; set; }
    }
}

crisischeckin/crisicheckinweb/Controllers/ClusterCoordinatorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using crisicheckinweb.ViewModels;
using Models;
using Services.Interfaces;

namespace crisicheckinweb.Controllers
{

    
    public class ClusterCoordinatorController : BaseController
    {
        readonly ICluster _cluster;
        readonly IClusterCoordinatorService _clusterCoordinatorService;
        readonly IDisaster _disaster;

        public ClusterCoordinatorController(
            IDisaster disaster,
            ICluster cluster,
            IClusterCoordinatorService clusterCoordinatorService)
        {
            _disaster = disaster;
            _cluster = cluster;
            _clusterCoordinatorService = clusterCoordinatorService;
        }

        [HttpGet]
        public ActionResult Index(int? id = -1)
        {
            if (id == -1)
                return RedirectToAction("List", "Disaster");
            var disaster = _disaster.Get(id.GetValueOrDefault());
            if (null == disaster)
                return RedirectToAction("List", "Disaster");
            var vm = GetDisasterClusterCoordinatorsViewModel(disaster);
            return View(vm);
        }

        DisasterClusterCoordinatorsViewModel GetDisasterClusterCoordinatorsViewModel(Disaster disaster)
        {
            IList<Person> allPersonDataForDisplay;
            var clusterCoordinators = _clusterCoordinatorService.GetAllCoordinatorsForDisplay(disaster.Id, out allPersonDataForDisplay);
            var allClusters = _cluster.GetList().ToList();
            var disasterClusterCoordinatorsViewModel =
                new DisasterClusterCoordinatorsViewModel
                {
                    DisasterName = disaster.Name,
                    DisasterId = disaster.Id,
                    Clusters = allClusters
                        .Select(c => new ClusterViewModel
                                     {
                                         Name = c.Name,
                                         Coordinators = clusterCoordinators
                                             .Where(x => x.ClusterId == c.Id)
                                             .Select(x => new ClusterCoordinatorViewModel
                                                          {
                                                              Name = x.Person.FullName,
                                                              Id = x.Id,
                                                          })
                                             .ToList(),
                                     })
                        .ToList(),
                    AvailableClusters = allClusters,
                    AvailablePeople = allPersonDataForDisplay
                };
            return disasterClusterCoordinatorsViewModel;
        }

        public PartialViewResult AssignCoordinator(AssignClusterCoordinatorViewModel clusterCoordinator)
        {
            _clusterCoordinatorService.AssignClusterCoordinator(
                clusterCoordinator.DisasterId,
                clusterCoordinator.SelectedClusterId,
                clusterCoordinator.SelectedPersonId);
            int disasterId = clusterCoordinator.DisasterId;
            var disasterClusterCoordinatorsViewModel = GetDisasterClusterCoordinatorsViewModel(new Disaster {Id = disasterId});
            return PartialView(disasterClusterCoordinatorsViewModel);
        }

        [HttpGet]
        public ActionResult ConfirmUnassignCoordinator(int id, int disasterId)
        {
            var clusterCoordinator = _clusterCoordinatorService.GetCoordinatorForUnassign(id);
            if (clusterCoordinator == null)
            {
                return RedirectToAction("Index", new { id = disasterId });
            }

            var vm = new UnassignClusterCoordinatorViewModel
                     {
                         DisasterId = clusterCoordinator.DisasterId,
                         CoordinatorId = id,
                         CoordinatorName = clusterCoordinator.Person.FullName,
                         ClusterName = clusterCoordinator.Cluster.Name,
                     };
            return View(vm);
        }

        [HttpPost]
        public ActionResult UnassignCoordinator(int id)
        {
            var clusterCoordinator = _clusterCoordinatorService.GetCoordinatorFullyLoaded(id);
            if (null == clusterCoordinator)
                return RedirectToAction("Index");
            _clusterCoordinatorService.UnassignClusterCoordinator(clusterCoordinator);
            return RedirectToAction("Index", new { id = clusterCoordinator.DisasterId });
        }

       
    }
}

crisischeckin/crisicheckinweb/Views/ClusterCoordinator/AssignCoordinator.cshtml
@model crisicheckinweb.ViewModels.DisasterClusterCoordinatorsViewModel

<table cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
    <tr class="ht-header">
        <th>Cluster</th>
        <th>Coordinator(s)</th>
    </tr>
    @foreach (var cluster in Model.Clusters)
    {
        <tr>
            <td>@cluster.Name</td>
            <td>
                @foreach (var coordinator in cluster.Coordinators)
                {
                    <div class="cluster-coordinator">
                        @coordinator.Name
                        <a class="close glyphicon glyphicon-remove" href="@Url.Action("ConfirmUnassignCoordinator", new {id=@coordinator.Id, disasterId=@Model.DisasterId})"></a>
                    </div>
                }
            </td>
        </tr>
    }
</table>

crisischeckin/crisicheckinweb/Views/ClusterCoordinator/ConfirmUnassignCoordinator.cshtml
@model crisicheckinweb.ViewModels.UnassignClusterCoordinatorViewModel

@{
    ViewBag.Title = "Confirm Cluster Coordinator Unassignment";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Confirm Unassignment</h3>

<div style="padding-bottom:20px;font-size:larger">
    Really remove <strong>@Model.CoordinatorName</strong> as a coordinator for <strong>@Model.ClusterName</strong>?
</div>

@using (Html.BeginForm("UnassignCoordinator", "ClusterCoordinator", new {id=@Model.CoordinatorId}))
{
    @Html.AntiForgeryToken()
    <input class="ui-button" type="submit" value="Yes, please!"/>
}
<a class="ui-button" href="@Url.Action("Index", new {id=@Model.DisasterId})">No, please take me back.</a>

crisischeckin/crisicheckinweb/Views/ClusterCoordinator/Index.cshtml
@model crisicheckinweb.ViewModels.DisasterClusterCoordinatorsViewModel
@{
    ViewBag.Title = "View / Edit Cluster Coordinators";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h3>Cluster Coordinators for @Model.DisasterName</h3>
    <hr />
</div>
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <div id="coordinators">
        @Html.Partial("AssignCoordinator", Model)
    </div>
</div>
<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    <h3>Assign Cluster Coordinator </h3>
    <hr />
    @using (Ajax.BeginForm("AssignCoordinator", "ClusterCoordinator", new AjaxOptions() { UpdateTargetId = "coordinators" }))
    {
        @Html.HiddenFor(m => m.DisasterId)
        <div class="form-group">
            @Html.LabelFor(m => m.AvailableClusters, "Available Clusters: ")
            @Html.DropDownListFor(m => m.SelectedClusterId, new SelectList(Model.AvailableClusters, "Id", "Name", Model.SelectedClusterId), "-- Choose One --", new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AvailablePeople, "Available People: ")
            @if (Model.AvailablePeople.Any())
            {
                @Html.DropDownListFor(m => m.SelectedPersonId, new SelectList(Model.AvailablePeople, "Id", "FullName", Model.SelectedPersonId), "-- Choose One --", new {@class = "form-control"})
            }
            else
            {
                <span>No people available.</span>
            }
        </div>

        <input class="btn btn-black" id="AddButton" type="submit" value="Assign Coordinator" />
    }
</div><!-- /end of grid div -->