crisischeckin/crisicheckinweb/ViewModels/ListByDisasterViewModel.cs
using Models;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crisicheckinweb.ViewModels
{
    public class ListByDisasterViewModel
    {
        public IEnumerable<Disaster> Disasters { get; set; }
        public int SelectedDisaster { get; set; }
        public DateTime? CommitmentDate { get; set; }


        public int AddContactId { get; set; }
    }
}

crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Models;

namespace crisicheckinweb.ViewModels
{
    public class VolunteerViewModel
    {
        public IEnumerable<Disaster> Disasters { get; set; }
        public IEnumerable<DisasterCluster> DisasterClusters { get; set; }
        public IEnumerable<Commitment> MyCommitments { get; set; }
        public IEnumerable<Resource> MyOrgResources { get; set; }
        public IEnumerable<AvailableAction> AvailableActions { get; set; }
        public int RemoveCommitmentId { get; set; }
        public int RemoveResourceId { get; set; }
        public int PersonId { get; set; }
        [DisplayName("Disaster")]
        public int SelectedDisasterId { get; set; }
        [DisplayName("Activity")]
        public int SelectedClusterId { get; set; }
        [DisplayName("Start Date")]
        public DateTime SelectedStartDate { get; set; }
        [DisplayName("End Date")]
        public DateTime SelectedEndDate { get; set; }
        [DisplayName("Location")]
        public int VolunteerType { get; set; }
        [DisplayName("Location Detail")]
        public string Location { get; set; }

        [DisplayName("Start Date")]
        public DateTime ResourceStartDate { get; set; }
        [DisplayName("End Date")]
        public DateTime ResourceEndDate { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }
        [DisplayName("Quantity")]
        public int Qty { get; set; }
        [DisplayName("Resource Type")]
        public int SelectedResourceTypeId { get; set; }
        public IEnumerable<ResourceType> ResourceTypes { get; set; }

        public IEnumerable<VolunteerType> VolunteerTypes { get; set; }
        public Person Person { get; set; }
        public IEnumerable<ClusterCoordinator> ClusterCoordinators { get; set; }
    }
}

crisischeckin/crisicheckinweb/Controllers/VolunteerController.cs
using Services;
using Services.Interfaces;
using System;
using System.Web.Mvc;
using System.Linq;
using crisicheckinweb.ViewModels;
using Common;
using Models;
using System.Collections.Generic;
using crisicheckinweb.Wrappers;

namespace crisicheckinweb.Controllers
{
    public class VolunteerController : BaseController
    {
        private readonly IDisaster _disasterSvc;
        private readonly ICluster _clusterSvc;
        private readonly IAdmin _adminSvc;
        private readonly IMessageService _messageSvc;
        private readonly IVolunteerService _volunteerSvc;
        private readonly IWebSecurityWrapper _webSecurity;

        public VolunteerController(IDisaster disasterSvc, ICluster clusterSvc, IAdmin adminSvc, IMessageService messageSvc, IVolunteerService volunteerSvc, IWebSecurityWrapper webSecurity)
        {
            _disasterSvc = disasterSvc;
            _clusterSvc = clusterSvc;
            _adminSvc = adminSvc;
            _messageSvc = messageSvc;
            _volunteerSvc = volunteerSvc;
            _webSecurity = webSecurity;
        }

        [HttpGet]
        public ActionResult ListByDisaster()
        {
            var model = new ListByDisasterViewModel { Disasters = _disasterSvc.GetActiveList(), CommitmentDate = null };
            return View(model);
        }

        [HttpGet]
        public ActionResult ListResourceCheckinsByDisaster()
        {
            var model = new ListByDisasterViewModel { Disasters = _disasterSvc.GetActiveList(), CommitmentDate = null };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddContact(ListByDisasterViewModel model)
        {
            try
            {
                var person = _volunteerSvc.FindByUserId(_webSecurity.CurrentUserId);
                if (!person.OrganizationId.HasValue)
                {
                    throw new ArgumentException("Signed in User is not part of an Organization");
                }

                _adminSvc.AddContactForOrganization(person.OrganizationId.Value, model.AddContactId);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            var viewModel = new ListByDisasterViewModel
            {
                Disasters = _disasterSvc.GetActiveList(),
                SelectedDisaster = model.SelectedDisaster,
                CommitmentDate = model.CommitmentDate
            };
            return View("ListByDisaster", viewModel);
        }


        [HttpGet]
        public ActionResult CreateMessageToVolunteersByDisaster(int id)
        {
            var model = new SendMessageToAllVolunteersByDisasterViewModel { DisasterId = id };
            PopulateSendMessageViewModel(model);
            // Default subject to disaster name so they can type just a message if they want to.
            model.Subject = model.DisasterName;
            return View("CreateMessage", model);
        }

        private void PopulateSendMessageViewModel(SendMessageToAllVolunteersByDisasterViewModel model)
        {
            model.DisasterName = _disasterSvc.GetName(model.DisasterId);
            model.Clusters = _clusterSvc.GetList();
        }

        [HttpPost]
        public ActionResult SendMessageToVolunteersByDisaster(SendMessageToAllVolunteersByDisasterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                PopulateSendMessageViewModel(model);
                return View("CreateMessage", model);
            }
            else if (model.IsSMSMessage && model.Message.Length > Constants.TwilioMessageLength)
            {
                PopulateSendMessageViewModel(model);
                ModelState["Message"].Errors.Add(string.Format("The message cannot have more than {0} characters when submiting as a SMS.", Constants.TwilioMessageLength));
                return View("CreateMessage", model);
            }

            var sender = model.DisasterName + " - Coordinator";
            var recipientCriterion = new RecipientCriterion(model.DisasterId, model.SelectedClusterIds, model.ClusterCoordinatorsOnly, model.CheckedInOnly);
            var message = new Message(model.Subject, model.Message) { IsSMSMessage = model.IsSMSMessage };

            _messageSvc.SendMessageToDisasterVolunteers(message, recipientCriterion, sender);

            return View(model);
        }

        [HttpPost]
        public PartialViewResult Filter(ListByDisasterViewModel model)
        {
            var result = new CheckinListsResultsViewModel();

            if (model.SelectedDisaster != 0)
            {
                result.OrganizationContacts = _adminSvc.GetContactsForDisaster(model.SelectedDisaster).ToList();

                var volunteers = _adminSvc.GetVolunteersForDisaster(model.SelectedDisaster, model.CommitmentDate);

                if (model.CommitmentDate == null)
                {
                    result.VolunteerCheckins = (from person in volunteers
                                                select new Person
                                                {
                                                    Commitments = person.Commitments.Where(x => x.DisasterId == model.SelectedDisaster).ToList(),
                                                    Email = person.Email,
                                                    FirstName = person.FirstName,
                                                    Organization = person.Organization,
                                                    OrganizationId = person.OrganizationId,
                                                    Id = person.Id,
                                                    LastName = person.LastName,
                                                    PhoneNumber = person.PhoneNumber,
                                                    UserId = person.UserId
                                                }).ToList();

                }
                else
                {
                    result.VolunteerCheckins = (from person in volunteers
                                                select new Person
                                                {
                                                    Commitments = person.Commitments.Where(x => x.DisasterId == model.SelectedDisaster
                                                        && model.CommitmentDate >= x.StartDate
                                                        && model.CommitmentDate <= x.EndDate).ToList(),
                                                    Email = person.Email,
                                                    FirstName = person.FirstName,
                                                    Id = person.Id,
                                                    LastName = person.LastName,
                                                    PhoneNumber = person.PhoneNumber,
                                                    UserId = person.UserId
                                                }).ToList();

                }
            }

            return PartialView("_FilterResults", result);
        }


        [HttpPost]
        public PartialViewResult FilterResourceCheckins(ListByDisasterViewModel model)
        {
            var result = new CheckinListsResultsViewModel();

            if (model.SelectedDisaster != 0)
            {
                result.ResourceCheckins = _adminSvc.GetResourceCheckinsForDisaster(model.SelectedDisaster, model.CommitmentDate).ToList();
            }

            return PartialView("_FilterResourceCheckinResults", result);
        }
    }
}

crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml
@using Common
@using Microsoft.Web.Mvc
@model crisicheckinweb.ViewModels.SendMessageToAllVolunteersByDisasterViewModel
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Send Message To Volunteers By Disaster";
}

<div class="col-lg-6 col-sm-12 col-xs-12 col-md-6">
    @using (Html.BeginForm("SendMessageToVolunteersByDisaster", "Volunteer"))
    {
        @Html.HiddenFor(m => m.DisasterId)

        <h3>Send Message To Volunteers: @Model.DisasterName</h3>
        @Html.ValidationSummary()

        <div class="form-group required">
            @Html.LabelFor(m => m.Subject)
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
        </div>
        <div class="form-group required">
            @Html.LabelFor(m => m.SelectedClusterIds)
            @Html.ListBoxFor(m => m.SelectedClusterIds,
                new MultiSelectList(@Model.Clusters, "Id", "Name", @Model.SelectedClusterIds),
                new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.CheckBoxFor(m => m.ClusterCoordinatorsOnly)
            @Html.LabelFor(m => m.ClusterCoordinatorsOnly)
        </div>
        <div class="form-group">
            @Html.CheckBoxFor(m => m.CheckedInOnly)
            @Html.LabelFor(m => m.CheckedInOnly)
        </div>
        <div class="form-group">
            @Html.CheckBoxFor(m => m.IsSMSMessage)
            @Html.LabelFor(m => m.IsSMSMessage)
        </div>
        <div class="form-group required">
            @Html.LabelFor(m => m.Message)
            @Html.TextAreaFor(m => m.Message, 25, 76, new { @class = "form-control" })
        </div>

        <div class="form-group pull-right">
            <input type="submit" value="Send" class="btn btn-success" />
            <span id="warningMessage"></span>
        </div>
    }
</div>

@section scripts
{
    <script type="text/javascript">
        (function($) {
            $('#Message').bind('keyup', function() {
                ValidateMessageLength();
            });

            $('#IsSMSMessage').click(function () {
                ValidateMessageLength();
            });

            ValidateMessageLength();

        })(jQuery);

        function ValidateMessageLength() {

            var messageLength = $('#Message').val().length;
            var isSMS = $('#IsSMSMessage').prop('checked');
            var errorMessage = "";
            var isValid = true;
            var smsMaxLength = parseInt('@Constants.TwilioMessageLength');
            if (isSMS === true) {
                if (messageLength > smsMaxLength - 30) {
                    errorMessage = 'The message can only be ' + smsMaxLength + ' characters long. It is currently ' + messageLength;
                    if (messageLength > smsMaxLength) {
                        isValid = false;
                    } else {
                        isValid = true;
                    }
                } else {
                    errorMessage = "";
                }
            } else {
                if (messageLength > 600) {
                    errorMessage = 'The message can only be 640 characters long. It is currently ' + messageLength;
                    if (messageLength > 640) {
                        isValid = false;
                    } else {
                        isValid = true;
                    }
                } else {
                    errorMessage = "";
                }
            }

            $('#warningMessage').text(errorMessage);
            if (isValid === true)
                $('#warningMessage').css("color", "black");
            else
                $('#warningMessage').css("color", "red");

        }
    </script>
}

crisischeckin/crisicheckinweb/Views/Volunteer/ListByDisaster.cshtml
@model crisicheckinweb.ViewModels.ListByDisasterViewModel
@{
    ViewBag.Title = "List Checkins";
    if (User.IsInRole("Admin"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_VolunteerLayout.cshtml";
    }
}

<h2>@ViewBag.Title</h2>
@using (Ajax.BeginForm("Filter", "Volunteer", new AjaxOptions() { UpdateTargetId = "results" }))
{
    <div class="form-inline form-group">
        <text>Disaster: </text>@Html.DropDownListFor(m => m.SelectedDisaster, new SelectList(Model.Disasters, "Id", "Name", Model.SelectedDisaster), "-- Choose One --", new { @class = "form-control" })

        <text>Filter by Date: </text>@Html.TextBoxFor(m => m.CommitmentDate, new { id = "dp_startDate", @class="form-control" })
        <input class="btn btn-black" id="GoButton" type="submit" value="Go" />
    </div>
}
<div id="results"></div>

@section scripts
{
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                $("#dp_startDate").datepicker();
            });
        })(jQuery);
    </script>
}

crisischeckin/crisicheckinweb/Views/Volunteer/ListResourceCheckinsByDisaster.cshtml
@model crisicheckinweb.ViewModels.ListByDisasterViewModel
@{
    ViewBag.Title = "List Field Data";
    if (User.IsInRole("Admin"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    } else {
        Layout = "~/Views/Shared/_VolunteerLayout.cshtml";
    }
}


<h2>@ViewBag.Title</h2>
@using (Ajax.BeginForm("FilterResourceCheckins", "Volunteer", new AjaxOptions() { UpdateTargetId = "results" }))
{
    <div class="form-inline form-group">
        <text>Disaster: </text>@Html.DropDownListFor(m => m.SelectedDisaster, new SelectList(Model.Disasters, "Id", "Name", Model.SelectedDisaster), "-- Choose One --", new { @class = "form-control" })

        <text>Filter by Date: </text>@Html.TextBoxFor(m => m.CommitmentDate, new { id = "dp_startDate", @class = "form-control" })
        <input class="btn btn-black" id="GoButton" type="submit" value="Go" />
    </div>
}

<div id="results"></div>

@section scripts
{
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                $("#dp_startDate").datepicker();
            });
        })(jQuery);
    </script>
}

crisischeckin/crisicheckinweb/Views/Volunteer/SendMessageToVolunteersByDisaster.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Send Message To Volunteers By Disaster";
}

<h2>Send Message To Volunteers</h2>

<div>
    <p>The message has been processed.</p>
</div>

crisischeckin/crisicheckinweb/Views/Volunteer/_FilterResourceCheckinResults.cshtml
@model crisicheckinweb.ViewModels.CheckinListsResultsViewModel
@{
    ViewBag.Title = "_FilterResourceCheckinResults";    
}

<style>
    table, tr, th, td {
        padding: 7px;
        border: 1px solid grey;
    }
</style>

<h3>Field Reported Data</h3>
<table>
    <tr>
        <th>Entry Made</th>
        <th>Description</th>
        <th>Organization</th>
        <th>Quantity</th>
        <th>Type</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Location</th>
    </tr>
    @if (Model.ResourceCheckins != null)
    {
        foreach (var resource in Model.ResourceCheckins)
        {
            <tr>
                <td>@resource.EntryMade.ToShortDateString() @resource.EntryMade.ToShortTimeString()</td>
                <td>@resource.Description</td>
                <td>@(resource.Allocator != null ? resource.Allocator.OrganizationName  : "none") @if (resource.Person != null) { @("- " + resource.Person.FullName)}</td>
                <td>@resource.Qty </td>
                <td>@resource.ResourceType.TypeName</td>
                <td>@resource.StartOfAvailability.ToShortDateString()</td>
                <td>@resource.EndOfAvailability.ToShortDateString()</td>
                <td>@resource.Location.AddressLine1</td>
            </tr>
        }
    }
</table>

crisischeckin/crisicheckinweb/Views/Volunteer/_FilterResults.cshtml
@model crisicheckinweb.ViewModels.CheckinListsResultsViewModel
@{
    ViewBag.Title = "_FilterResults";    
}

<style>
    table, tr, th, td {
        padding: 7px;
        border: 1px solid grey;
    }
</style>

<h3>Volunteer Checkins</h3>
<table>
    <tr>
        <th>Volunteer Name</th>
        <th>Organization</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Activity</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Location</th>
    </tr>
    @if (Model.VolunteerCheckins != null)
    {
        foreach (var person in Model.VolunteerCheckins)
        {
            for (int ci = 0; ci < person.Commitments.Count(); ci++)
            {
                var commitment = person.Commitments.ElementAt(ci);

                <tr>
                    @if (ci == 0)
                    {
                        <td rowspan="@person.Commitments.Count()">@(person.LastName + ", " + person.FirstName)<br />
                            @using (Html.BeginForm("AddContact", "Volunteer", FormMethod.Post, new { @class = "navbar-form" }))
                            {
                              @Html.AntiForgeryToken()
                              @Html.HiddenFor(m => m.AddContactId, new { @Value = person.Id })
                              <button class="btn btn-black btn-xs" type="submit">Add as Contact</button>
                            }                        
                        </td>
                        <td rowspan="@person.Commitments.Count()">@(person.Organization != null ? person.Organization.OrganizationName : "none")</td>
                        <td rowspan="@person.Commitments.Count()">@person.Email</td>
                        <td rowspan="@person.Commitments.Count()">@person.PhoneNumber</td>
                    }
                    <td>@commitment.Cluster.Name</td>
                    <td>@commitment.StartDate.ToShortDateString()</td>
                    <td>@commitment.EndDate.ToShortDateString()</td>
                    <td>
                        @commitment.VolunteerType.Name
                        @if (!String.IsNullOrWhiteSpace(commitment.Location))
                        {
                            @(" (" + commitment.Location + ")")
                        }
                    </td>
                </tr>
            }
        }
    }
</table>    

<h3>Organization Contacts</h3>
<table>
    <tr>
        <th>Organization</th>
        <th>Contact Name</th>
        <th>Contact Organization</th>
        <th>Email</th>
        <th>Phone</th>
    </tr>
    @if (Model.OrganizationContacts != null)
    {
        foreach (var contact in Model.OrganizationContacts)
        {
                <tr>
                    <td>@contact.Organization.OrganizationName</td>
                    <td>@(contact.Person.LastName + ", " + contact.Person.FirstName)</td>
                    <td>@(contact.Person.Organization != null ? contact.Person.Organization.OrganizationName : "none")</td>
                    <td>@contact.Person.Email</td>
                    <td>@contact.Person.PhoneNumber</td>
                </tr>
        }
    }
</table>